[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = [
  "cd ai_backend && pip install --upgrade pip",
  "cd ai_backend && pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase completed'"]

[start]
cmd = "cd ai_backend && gunicorn --workers 1 --threads 1 --timeout 180 --bind 0.0.0.0:$PORT 'src.detector:app'"
